# Generated by Django 5.1.7 on 2026-03-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_livro_autor_livro_categoria_livro_editora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=13, null=True),
        ),
    ]
