# Generated by Django 5.1.7 on 2026-03-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_livro_isbn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='descricao',
            new_name='nome',
        ),
    ]
